### ISSUE TITLE
READMEの修正

### ISSUE THREAD

**Issue by asaduke** [asaduke/LivePlanningManager#64]
## 概要
MVPに入れていた「LINE通知機能」と「テスト機能」をその後の機能に変更したいと思っております。

## 理由
体調不良で一ヶ月以上思うように実装が進められておらず、今の集中力と体力では、LINE通知機能とテスト機能をMVPに含めることは困難であると判断しました。

### 変更前
実装を予定している機能
MVP
・ユーザー登録機能
・ログイン, ログアウト機能
・パスワード再設定機能
・ライブ登録機能
・持ち物リスト一覧機能
_・LINE通知機能(LINE Messaging API)
・テスト機能(RSpec)_

その後の機能
・ユーザープロフィール機能
・持ち物リスト投稿機能
・タグ機能
・お気に入り機能
・マルチ検索, オートコンプリート機能
・管理ユーザー機能
・SNS共有機能
・PWA機能

### 変更後
実装を予定している機能
MVP
・ユーザー登録機能
・ログイン, ログアウト機能
・パスワード再設定機能
・ライブ登録機能
・持ち物リスト一覧機能

その後の機能
・ユーザープロフィール機能
・持ち物リスト投稿機能
・タグ機能
・お気に入り機能
・マルチ検索, オートコンプリート機能
・管理ユーザー機能
・SNS共有機能
・PWA機能
_・LINE通知機能(LINE Messaging API)
・テスト機能(RSpec)_

**Comment by Tsuchiya2** [comment]
変更承知しました。
変更後の内容で進めてください。

**Comment by asaduke** [comment]
ご確認いただき、ありがとうございました。
