### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by kenchasonakai** [asaduke/LivePlanningManager#74]
MVPリリースおめでとうございます！
このissueのコメントで本リリースの予定日の回答をお願いいたします
以下にレビュー内容記載します

Hotwireを使って画面遷移を伴わない機能を作れているところ良いと思います
まだ本リリースまで開発する予定のものが多く残っているかと思いますので引き続き開発を続けていきましょう
また、イメージしているものに合いそうだったらカレンダーを使って予定を視覚的にわかりやすくしたりしても良いかなと思います
機能以外で技術的にアピールできるポイントとして下記のようなものがありますのでご自身の余力に合わせて取り入れると良いかと思います

- 独自ドメイン
- GitHubActionsを使った、GitHub上での自動テスト実行機能・自動デプロイ機能
- Dockerを使った開発環境の構築

**Comment by asaduke** [comment]
レビューありがとうございます！
ご意見、参考にさせていただきissueに追加しました。
本リリースの予定日は、4/30です。
よろしくお願いいたします。
